apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ml-pipeline.fullname" . }}-config
  labels:
    {{- include "ml-pipeline.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.app.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  POSTGRES_HOST: {{ include "ml-pipeline.fullname" . }}-postgresql
  POSTGRES_PORT: "5432"
  REDIS_HOST: {{ include "ml-pipeline.fullname" . }}-redis-master
  REDIS_PORT: "6379"
