apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ml-pipeline.fullname" . }}-secret
  labels:
    {{- include "ml-pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET_KEY: {{ .Values.app.secrets.JWT_SECRET_KEY | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}
